syntax on
filetype on
filetype plugin on
filetype indent on

set nocompatible
set runtimepath^=~/.vim/bundle/ctrlp.vim
set number
set ruler
set showcmd
set expandtab
set autoindent
set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch
set clipboard=unnamed
set pastetoggle=<C-L>

let g:ctrlp_custom_ignore = {
  \ 'dir': 'node_modules'
  \ }
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0

nnoremap <leader><space> :nohlsearch<CR>
nnoremap j gj
nnoremap k gk
nnoremap <C-N> :set invnumber<CR>

vmap <TAB> >gv
vmap <S-TAB> <gv

autocmd BufWritePre * :%s/\s\+$//e
